---
title: "Regresiones lineales"
author: "Máximo Quiroz Sánchez"
format: html
editor: visual
---

# Importación de librerías

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

```

# Cargar datos

```{python}
inegi_data = pd.read_excel("C:/Users/maxim/OneDrive/Documentos/Análisis Númerico/inegi_subdata.xlsx")
print(inegi_data.columns.tolist())
```

# Análisis de correlación

```{python}
data_numeric = inegi_data.select_dtypes(include=np.number)
corr = data_numeric.corr()
print("Análisis de Correlación:")
display(corr)

plt.figure(figsize=(8, 5))
sns.heatmap(
    corr, annot=True, cmap='coolwarm', 
    annot_kws={"size":5}
)
plt.title('Matriz de Correlación', fontsize=10)
plt.xticks(rotation=45, ha='right', fontsize=5)
plt.yticks(fontsize=5)
plt.tight_layout()
plt.show()
```

# Modelos de Regresión Lineal Simple

## Indicador Global de Actividad Económica \~ Actividad Industrial

```{python}
X = inegi_data['Actividad_Industrial']
y = inegi_data['IGAE']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())
```

*Interpretación del modelo:*\
El análisis muestra que la actividad industrial tiene un impacto importante en el indicador global de actividad económica. Por cada punto que aumenta la actividad industrial, el indicador global crece proporcionalmente. El valor de R² indica cuánta proporción de la variabilidad total es explicada por la actividad industrial.

## Indice de Precios al Consumidor \~ Actividades Primarias 

```{python}
X = inegi_data['Actividades_Primarias']
y = inegi_data['Indice de Precios_Consumidor']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())
```

```{python}
plt.figure()
sns.regplot(x='Actividades_Primarias', y='Indice de Precios_Consumidor', data=inegi_data, color='purple', line_kws={'color':'green'})
plt.title("Precios al Consumidor vs Actividades Primarias")
plt.xlabel("Actividades Primarias")
plt.ylabel("Precios al Consumidor")
plt.tight_layout()
plt.show()
```

*Interpretación del modelo:*\
El análisis muestra que las actividades primarias tienen un impacto importante en el índice de precios al consumidor. Por cada punto que aumentan las actividades primarias, el índice de precios al consumidor crecen en promedio 1.09 puntos . El valor de R² indica que aproximadamente el 48% de la variabilidad total del índice de precios al consumidor es explicada por las actividades primarias.

## Exportaciones Totales \~ Importaciones Totales

```{python}
X = inegi_data['Importaciones_Totales']
y = inegi_data['Exportaciones_Totales']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())
```

```{python}
plt.figure()
sns.regplot(x='Importaciones_Totales', y='Exportaciones_Totales', data=inegi_data, color='orange', line_kws={'color':'blue'})
plt.title("Exportaciones Totales vs Importaciones Totales")
plt.xlabel("Importaciones Totales")
plt.ylabel("Exportaciones Totales")
plt.tight_layout()
plt.show()
```

*Interpretación del modelo:*\
El análisis muestra que las importaciones totales tienen un impacto importante en las exportaciones totales. Por cada punto que aumentan las importaciones totales, las exportaciones totales crecen proporcionalmente. El valor de R² indica cuánta proporción de la variabilidad total de las exportaciones totales es explicada por las importaciones totales.

## Actividades terciarias \~ Indicador Global de Actividad Económica

```{python}
X = inegi_data['IGAE']
y = inegi_data['Actividades_Terciarias']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())
```

```{python}
plt.figure()
sns.regplot(x='IGAE', y='Actividades_Terciarias', data=inegi_data, color='blue', line_kws={'color':'brown'})
plt.title("Actividades Terciarias vs Indicador Global de Actividad Económica")
plt.xlabel("Indicador Global de Actividad Económica")
plt.ylabel("Actividad Industrial")
plt.tight_layout()
plt.show()
```

*Interpretación del modelo:*\
El análisis muestra que el Indicador Global de la Actividad Económica (IGAE) tiene un impacto importante en las actividades terciarias. Por cada punto que aumenta el IGAE, las actividades terciarias crecen en promedio 1.14 puntos. El valor de R² indica que aproximadamente el 99% de la variabilidad total de las actividades terciarias es explicada por el IGAE.

## Importaciones No Petroleras \~ Exportaciones No Petroleras

```{python}
X = inegi_data['Exportaciones_No_Petroleras']
y = inegi_data['Importaciones_No_Petroleras']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())
```

```{python}
plt.figure()
sns.regplot(x='Exportaciones_No_Petroleras', y='Importaciones_No_Petroleras', data=inegi_data, color='yellow', line_kws={'color':'purple'})
plt.title("Importaciones No Petroleras vs Exportaciones No Petroleras")
plt.xlabel("Exportaciones No Petroleras")
plt.ylabel("Importaciones No Petroleras")
plt.tight_layout()
plt.show()
```

Interpretación del modelo:

El análisis muestra que las exportaciones no petroleras tienen un impacto importante en las importaciones no petroleras. Por cada punto que aumentan las exportaciones no petroleras, las importaciones no petroleras crecen en promedio 0.93 puntos. El valor de R² indica que aproximadamente el 98% de la variabilidad total de las importaciones no petroleras es explicada por las exportaciones no petroleras.

# Modelos de Regresión Lineal Múltiple

## Indicador Global de Actividad Económica \~ Actividades Terciarias+ Actividad Industrial

```{python}
X = inegi_data[['Actividades_Terciarias', 'Actividad_Industrial']]
y = inegi_data['IGAE']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())
```

# Análisis con Acciones

```{python}
from IPython.display import display
import pandas as pd
e_cierre = pd.read_excel("C:/Users/maxim/OneDrive/Documentos/Análisis Númerico/Maximo_Quiroz_Tarea_3.xlsx")
data_numeric = e_cierre.select_dtypes(include=np.number)
corr = data_numeric.corr()
print("Análisis de Correlación Acciones:")
display(corr)

plt.figure(figsize=(8,5))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Matriz de Correlación - Acciones')
plt.tight_layout()
plt.show()
```

# Regresiones Lineales Múltiples Acciones

## Apple vs Amazon

```{python}
X = e_cierre['Amazon.Close']
y = e_cierre['Apple.Close']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())

from IPython.display import display
import pandas as pd

df = pd.DataFrame({'a': [1,2], 'b': [3,4]})
display(df) 
plt.figure()
sns.regplot(x='Amazon.Close', y='Apple.Close', data=e_cierre, color='orange', line_kws={'color':'blue'})
plt.title("Apple vs Amazon")
plt.xlabel("Amazon")
plt.ylabel("Apple")
plt.tight_layout()
plt.show()
```

Interpretación del modelo:

El análisis indica que existe una relación positiva entre el precio de cierre de Amazon y el precio de cierre de Apple. De acuerdo con el modelo, por cada punto que aumenta el precio de cierre de Amazon, el de Apple tiende a aumentar en promedio 0.73 puntos. El coeficiente de determinación (R²) es de 0.34, lo que significa que aproximadamente el 34% de la variabilidad en el precio de cierre de Apple puede explicarse por el precio de cierre de Amazon. Aunque la relación es estadísticamente significativa, el modelo solo explica una parte moderada de la variabilidad observada en los precios de cierre de Apple.

## Google vs Microsoft

```{python}
X = e_cierre['Microsoft.Close']
y = e_cierre['Google.Close']
X_const = sm.add_constant(X)
modelo = sm.OLS(y, X_const).fit()
print(modelo.summary())

plt.figure()
sns.regplot(x='Microsoft.Close', y='Google.Close', data=e_cierre, color='green', line_kws={'color':'purple'})
plt.title("Google vs Microsoft")
plt.xlabel("Microsoft")
plt.ylabel("Google")
plt.tight_layout()
plt.show()
```

Interpretación del modelo:

El análisis muestra que existe una fuerte relación positiva entre el precio de cierre de Microsoft y el precio de cierre de Google. Según el modelo, por cada punto que aumenta el precio de cierre de Microsoft, el de Google aumenta en promedio 0.40 puntos. El coeficiente de determinación (R²) es de 0.89, lo que indica que aproximadamente el 89% de la variabilidad en el precio de cierre de Google puede explicarse por el precio de cierre de Microsoft. Esto sugiere que el modelo tiene un alto poder explicativo para la relación entre ambas acciones.
